/*
 * Ours
 *
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Com.OursPrivacy.Api;
using Com.OursPrivacy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Com.OursPrivacy.Test.Api
{
    /// <summary>
    ///  Class for testing OursPrivacyApi
    /// </summary>
    public sealed class OursPrivacyApiTests : ApiTestsBase
    {
        private readonly IOursPrivacyApi _instance;

        public OursPrivacyApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IOursPrivacyApi>();
        }

        /// <summary>
        /// Test Identify
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task IdentifyAsyncTest()
        {
            IdentifyRequest identifyRequest = default!;
            var response = await _instance.IdentifyAsync(identifyRequest);
            var model = response.Ok();
            Assert.IsType<Track200Response>(model);
        }

        /// <summary>
        /// Test Track
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task TrackAsyncTest()
        {
            TrackRequest trackRequest = default!;
            var response = await _instance.TrackAsync(trackRequest);
            var model = response.Ok();
            Assert.IsType<Track200Response>(model);
        }
    }
}
