/*
 * Ours
 *
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.OursPrivacy.Model;
using Com.OursPrivacy.Client;
using System.Reflection;

namespace Com.OursPrivacy.Test.Model
{
    /// <summary>
    ///  Class for testing IdentifyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentifyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentifyRequest
        //private IdentifyRequest instance;

        public IdentifyRequestTests()
        {
            // TODO uncomment below to create an instance of IdentifyRequest
            //instance = new IdentifyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentifyRequest
        /// </summary>
        [Fact]
        public void IdentifyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentifyRequest
            //Assert.IsType<IdentifyRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'UserProperties'
        /// </summary>
        [Fact]
        public void UserPropertiesTest()
        {
            // TODO unit test for the property 'UserProperties'
        }

        /// <summary>
        /// Test the property 'DefaultProperties'
        /// </summary>
        [Fact]
        public void DefaultPropertiesTest()
        {
            // TODO unit test for the property 'DefaultProperties'
        }
    }
}
