/*
 * Ours
 *
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.OursPrivacy.Model;
using Com.OursPrivacy.Client;
using System.Reflection;

namespace Com.OursPrivacy.Test.Model
{
    /// <summary>
    ///  Class for testing Track200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Track200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Track200Response
        //private Track200Response instance;

        public Track200ResponseTests()
        {
            // TODO uncomment below to create an instance of Track200Response
            //instance = new Track200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Track200Response
        /// </summary>
        [Fact]
        public void Track200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Track200Response
            //Assert.IsType<Track200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
    }
}
