/*
 * Ours
 *
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.OursPrivacy.Model;
using Com.OursPrivacy.Client;
using System.Reflection;

namespace Com.OursPrivacy.Test.Model
{
    /// <summary>
    ///  Class for testing TrackRequestDefaultProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackRequestDefaultPropertiesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackRequestDefaultProperties
        //private TrackRequestDefaultProperties instance;

        public TrackRequestDefaultPropertiesTests()
        {
            // TODO uncomment below to create an instance of TrackRequestDefaultProperties
            //instance = new TrackRequestDefaultProperties();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackRequestDefaultProperties
        /// </summary>
        [Fact]
        public void TrackRequestDefaultPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackRequestDefaultProperties
            //Assert.IsType<TrackRequestDefaultProperties>(instance);
        }

        /// <summary>
        /// Test the property 'IsBot'
        /// </summary>
        [Fact]
        public void IsBotTest()
        {
            // TODO unit test for the property 'IsBot'
        }

        /// <summary>
        /// Test the property 'AdId'
        /// </summary>
        [Fact]
        public void AdIdTest()
        {
            // TODO unit test for the property 'AdId'
        }

        /// <summary>
        /// Test the property 'AdsetId'
        /// </summary>
        [Fact]
        public void AdsetIdTest()
        {
            // TODO unit test for the property 'AdsetId'
        }

        /// <summary>
        /// Test the property 'CampaignId'
        /// </summary>
        [Fact]
        public void CampaignIdTest()
        {
            // TODO unit test for the property 'CampaignId'
        }

        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Fact]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }

        /// <summary>
        /// Test the property 'BrowserName'
        /// </summary>
        [Fact]
        public void BrowserNameTest()
        {
            // TODO unit test for the property 'BrowserName'
        }

        /// <summary>
        /// Test the property 'BrowserVersion'
        /// </summary>
        [Fact]
        public void BrowserVersionTest()
        {
            // TODO unit test for the property 'BrowserVersion'
        }

        /// <summary>
        /// Test the property 'CpuArchitecture'
        /// </summary>
        [Fact]
        public void CpuArchitectureTest()
        {
            // TODO unit test for the property 'CpuArchitecture'
        }

        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Fact]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }

        /// <summary>
        /// Test the property 'DeviceModel'
        /// </summary>
        [Fact]
        public void DeviceModelTest()
        {
            // TODO unit test for the property 'DeviceModel'
        }

        /// <summary>
        /// Test the property 'DeviceVendor'
        /// </summary>
        [Fact]
        public void DeviceVendorTest()
        {
            // TODO unit test for the property 'DeviceVendor'
        }

        /// <summary>
        /// Test the property 'EngineName'
        /// </summary>
        [Fact]
        public void EngineNameTest()
        {
            // TODO unit test for the property 'EngineName'
        }

        /// <summary>
        /// Test the property 'EngineVersion'
        /// </summary>
        [Fact]
        public void EngineVersionTest()
        {
            // TODO unit test for the property 'EngineVersion'
        }

        /// <summary>
        /// Test the property 'OsName'
        /// </summary>
        [Fact]
        public void OsNameTest()
        {
            // TODO unit test for the property 'OsName'
        }

        /// <summary>
        /// Test the property 'OsVersion'
        /// </summary>
        [Fact]
        public void OsVersionTest()
        {
            // TODO unit test for the property 'OsVersion'
        }

        /// <summary>
        /// Test the property 'BrowserLanguage'
        /// </summary>
        [Fact]
        public void BrowserLanguageTest()
        {
            // TODO unit test for the property 'BrowserLanguage'
        }

        /// <summary>
        /// Test the property 'CurrentUrl'
        /// </summary>
        [Fact]
        public void CurrentUrlTest()
        {
            // TODO unit test for the property 'CurrentUrl'
        }

        /// <summary>
        /// Test the property 'Webview'
        /// </summary>
        [Fact]
        public void WebviewTest()
        {
            // TODO unit test for the property 'Webview'
        }

        /// <summary>
        /// Test the property 'Iframe'
        /// </summary>
        [Fact]
        public void IframeTest()
        {
            // TODO unit test for the property 'Iframe'
        }

        /// <summary>
        /// Test the property 'SessionCount'
        /// </summary>
        [Fact]
        public void SessionCountTest()
        {
            // TODO unit test for the property 'SessionCount'
        }

        /// <summary>
        /// Test the property 'ActiveDuration'
        /// </summary>
        [Fact]
        public void ActiveDurationTest()
        {
            // TODO unit test for the property 'ActiveDuration'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Epik'
        /// </summary>
        [Fact]
        public void EpikTest()
        {
            // TODO unit test for the property 'Epik'
        }

        /// <summary>
        /// Test the property 'Sacid'
        /// </summary>
        [Fact]
        public void SacidTest()
        {
            // TODO unit test for the property 'Sacid'
        }

        /// <summary>
        /// Test the property 'Fbc'
        /// </summary>
        [Fact]
        public void FbcTest()
        {
            // TODO unit test for the property 'Fbc'
        }

        /// <summary>
        /// Test the property 'Fbclid'
        /// </summary>
        [Fact]
        public void FbclidTest()
        {
            // TODO unit test for the property 'Fbclid'
        }

        /// <summary>
        /// Test the property 'FbclidCreationTime'
        /// </summary>
        [Fact]
        public void FbclidCreationTimeTest()
        {
            // TODO unit test for the property 'FbclidCreationTime'
        }

        /// <summary>
        /// Test the property 'Fbp'
        /// </summary>
        [Fact]
        public void FbpTest()
        {
            // TODO unit test for the property 'Fbp'
        }

        /// <summary>
        /// Test the property 'GadSource'
        /// </summary>
        [Fact]
        public void GadSourceTest()
        {
            // TODO unit test for the property 'GadSource'
        }

        /// <summary>
        /// Test the property 'Gbraid'
        /// </summary>
        [Fact]
        public void GbraidTest()
        {
            // TODO unit test for the property 'Gbraid'
        }

        /// <summary>
        /// Test the property 'Gclid'
        /// </summary>
        [Fact]
        public void GclidTest()
        {
            // TODO unit test for the property 'Gclid'
        }

        /// <summary>
        /// Test the property 'Ndclid'
        /// </summary>
        [Fact]
        public void NdclidTest()
        {
            // TODO unit test for the property 'Ndclid'
        }

        /// <summary>
        /// Test the property 'Dclid'
        /// </summary>
        [Fact]
        public void DclidTest()
        {
            // TODO unit test for the property 'Dclid'
        }

        /// <summary>
        /// Test the property 'Qclid'
        /// </summary>
        [Fact]
        public void QclidTest()
        {
            // TODO unit test for the property 'Qclid'
        }

        /// <summary>
        /// Test the property 'RdtCid'
        /// </summary>
        [Fact]
        public void RdtCidTest()
        {
            // TODO unit test for the property 'RdtCid'
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }

        /// <summary>
        /// Test the property 'Msclkid'
        /// </summary>
        [Fact]
        public void MsclkidTest()
        {
            // TODO unit test for the property 'Msclkid'
        }

        /// <summary>
        /// Test the property 'LiFatId'
        /// </summary>
        [Fact]
        public void LiFatIdTest()
        {
            // TODO unit test for the property 'LiFatId'
        }

        /// <summary>
        /// Test the property 'Pathname'
        /// </summary>
        [Fact]
        public void PathnameTest()
        {
            // TODO unit test for the property 'Pathname'
        }

        /// <summary>
        /// Test the property 'Referrer'
        /// </summary>
        [Fact]
        public void ReferrerTest()
        {
            // TODO unit test for the property 'Referrer'
        }

        /// <summary>
        /// Test the property 'ScreenHeight'
        /// </summary>
        [Fact]
        public void ScreenHeightTest()
        {
            // TODO unit test for the property 'ScreenHeight'
        }

        /// <summary>
        /// Test the property 'ScreenWidth'
        /// </summary>
        [Fact]
        public void ScreenWidthTest()
        {
            // TODO unit test for the property 'ScreenWidth'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }

        /// <summary>
        /// Test the property 'UtmCampaign'
        /// </summary>
        [Fact]
        public void UtmCampaignTest()
        {
            // TODO unit test for the property 'UtmCampaign'
        }

        /// <summary>
        /// Test the property 'UtmContent'
        /// </summary>
        [Fact]
        public void UtmContentTest()
        {
            // TODO unit test for the property 'UtmContent'
        }

        /// <summary>
        /// Test the property 'UtmMedium'
        /// </summary>
        [Fact]
        public void UtmMediumTest()
        {
            // TODO unit test for the property 'UtmMedium'
        }

        /// <summary>
        /// Test the property 'UtmName'
        /// </summary>
        [Fact]
        public void UtmNameTest()
        {
            // TODO unit test for the property 'UtmName'
        }

        /// <summary>
        /// Test the property 'Ttclid'
        /// </summary>
        [Fact]
        public void TtclidTest()
        {
            // TODO unit test for the property 'Ttclid'
        }

        /// <summary>
        /// Test the property 'Twclid'
        /// </summary>
        [Fact]
        public void TwclidTest()
        {
            // TODO unit test for the property 'Twclid'
        }

        /// <summary>
        /// Test the property 'Clickid'
        /// </summary>
        [Fact]
        public void ClickidTest()
        {
            // TODO unit test for the property 'Clickid'
        }

        /// <summary>
        /// Test the property 'Clid'
        /// </summary>
        [Fact]
        public void ClidTest()
        {
            // TODO unit test for the property 'Clid'
        }

        /// <summary>
        /// Test the property 'Sccid'
        /// </summary>
        [Fact]
        public void SccidTest()
        {
            // TODO unit test for the property 'Sccid'
        }

        /// <summary>
        /// Test the property 'UtmSource'
        /// </summary>
        [Fact]
        public void UtmSourceTest()
        {
            // TODO unit test for the property 'UtmSource'
        }

        /// <summary>
        /// Test the property 'UtmTerm'
        /// </summary>
        [Fact]
        public void UtmTermTest()
        {
            // TODO unit test for the property 'UtmTerm'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Wbraid'
        /// </summary>
        [Fact]
        public void WbraidTest()
        {
            // TODO unit test for the property 'Wbraid'
        }

        /// <summary>
        /// Test the property 'Uafvl'
        /// </summary>
        [Fact]
        public void UafvlTest()
        {
            // TODO unit test for the property 'Uafvl'
        }

        /// <summary>
        /// Test the property 'PageHash'
        /// </summary>
        [Fact]
        public void PageHashTest()
        {
            // TODO unit test for the property 'PageHash'
        }

        /// <summary>
        /// Test the property 'Sid'
        /// </summary>
        [Fact]
        public void SidTest()
        {
            // TODO unit test for the property 'Sid'
        }

        /// <summary>
        /// Test the property 'NewS'
        /// </summary>
        [Fact]
        public void NewSTest()
        {
            // TODO unit test for the property 'NewS'
        }

        /// <summary>
        /// Test the property 'Fv'
        /// </summary>
        [Fact]
        public void FvTest()
        {
            // TODO unit test for the property 'Fv'
        }

        /// <summary>
        /// Test the property 'Sr'
        /// </summary>
        [Fact]
        public void SrTest()
        {
            // TODO unit test for the property 'Sr'
        }
    }
}
