/*
 * Ours
 *
 * The Ours Server-Side REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Com.OursPrivacy.Model;
using Com.OursPrivacy.Client;
using System.Reflection;

namespace Com.OursPrivacy.Test.Model
{
    /// <summary>
    ///  Class for testing TrackRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TrackRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TrackRequest
        //private TrackRequest instance;

        public TrackRequestTests()
        {
            // TODO uncomment below to create an instance of TrackRequest
            //instance = new TrackRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TrackRequest
        /// </summary>
        [Fact]
        public void TrackRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TrackRequest
            //Assert.IsType<TrackRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }

        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Fact]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Fact]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'EventProperties'
        /// </summary>
        [Fact]
        public void EventPropertiesTest()
        {
            // TODO unit test for the property 'EventProperties'
        }

        /// <summary>
        /// Test the property 'UserProperties'
        /// </summary>
        [Fact]
        public void UserPropertiesTest()
        {
            // TODO unit test for the property 'UserProperties'
        }

        /// <summary>
        /// Test the property 'DefaultProperties'
        /// </summary>
        [Fact]
        public void DefaultPropertiesTest()
        {
            // TODO unit test for the property 'DefaultProperties'
        }

        /// <summary>
        /// Test the property 'DistinctId'
        /// </summary>
        [Fact]
        public void DistinctIdTest()
        {
            // TODO unit test for the property 'DistinctId'
        }
    }
}
